spring.application.name=order-service
server.port=8084

services.product.url=${SERVICES_PRODUCT_URL:http://localhost:8082}

spring.datasource.url=${ORDER_DB_URL:jdbc:mysql://localhost:3307/mall_order}
spring.datasource.username=${ORDER_DB_USERNAME:mall}
spring.datasource.password=${ORDER_DB_PASSWORD:mall}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=order-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.libo.mall.*
spring.kafka.consumer.properties.spring.json.type.mapping=order-created:com.libo.mall.order.event.OrderCreatedEvent,stock-result:com.libo.mall.order.event.StockResultEvent
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=order-created:com.libo.mall.order.event.OrderCreatedEvent,stock-result:com.libo.mall.order.event.StockResultEvent
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true

mall.kafka.topics.order-created=order-created.v1
mall.kafka.topics.stock-result=stock-result.v1
mall.kafka.topics.partitions=3
mall.kafka.topics.replicas=1
mall.kafka.consumer.retry.interval-ms=1000
mall.kafka.consumer.retry.max-attempts=3
mall.outbox.publisher.fixed-delay-ms=1000
mall.outbox.publisher.batch-size=100
mall.outbox.publisher.send-timeout-seconds=10
mall.outbox.publisher.processing-timeout-seconds=60

management.endpoints.web.exposure.include=health,info
