apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: mall
spec:
  template:
    spec:
      containers:
        - name: order-service
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 512Mi
