apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - product-mysql.yaml
  - order-mysql.yaml
  - kafka.yaml
  - product-service.yaml
  - order-service.yaml
  - api-gateway.yaml
